sim/mahasiswa/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, PasswordField, SelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from sim.models import Tmahasiswa
from flask_wtf.file import FileField,FileAllowed

class mahasiswa_F(FlaskForm):
    npm = StringField('NPM',validators=[DataRequired()])
    nama = StringField('Nama',validators=[DataRequired()])
    email = StringField('Email',validators=[DataRequired(),Email()])
    kelas = StringField('Kelas',validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=20)])
    kon_pass = PasswordField('Konfirmasi Password', validators=[DataRequired(), EqualTo('password')])
    alamat = TextAreaField ('Alamat')
    submit = SubmitField('Tambah')

    #ceknpm
    def validate_npm(self,npm):
        ceknpm = Tmahasiswa.query.filter_by(npm=npm.data).first()
        if ceknpm:
            raise ValidationError('NPM sudah terdaftar, Gunakan NPM yang lain')

     #cekemail
    def validate_email(self,email):
        cekemail = Tmahasiswa.query.filter_by(email=email.data).first()
        if cekemail:
            raise ValidationError('Email sudah terdaftar, Gunakan Email yang lain')

class loginmahasiswa_F(FlaskForm):
    npm = StringField('NPM',validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Tambah')

class editmahasiswa_F(FlaskForm):
    npm = StringField('NPM',validators=[DataRequired()])
    nama = StringField('Nama',validators=[DataRequired()])
    email = StringField('Email',validators=[DataRequired(),Email()])
    kelas = StringField('Kelas',validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=20)])
    kon_pass = PasswordField('Konfirmasi Password', validators=[DataRequired(), EqualTo('password')])
    alamat = TextAreaField ('Alamat')
    foto = FileField('Ubah Foto Profil', validators=[FileAllowed(['jpg','png'])])
    submit = SubmitField('Ubah data')

    #ceknpm
    def validate_npm(self,npm):
        if npm.data != current_user.npm:
            ceknpm = Tmahasiswa.query.filter_by(npm=npm.data).first()
            if ceknpm:
                raise ValidationError('NPM sudah terdaftar, Gunakan NPM yang lain')

     #cekemail
    def validate_email(self,email):
        if email.data != current_user.email:
            cekemail = Tmahasiswa.query.filter_by(email=email.data).first()
            if cekemail:
                raise ValidationError('Email sudah terdaftar, Gunakan Email yang lain')

class pengaduan_F(FlaskForm):
    subjek = StringField('Subjek',validators=[DataRequired()])
    kategori= SelectField(u'Kategori Pengaduan', choices=[('administrasi','Pelayanan Administrasi'),('fasilitas','Fasilitas'), ('dosen','Dosen')], validators=[DataRequired()])
    detail_pengaduan= TextAreaField('Pengaduan')
    submit = SubmitField('Kirim')

class editpengaduan_F(FlaskForm):
    subjek = StringField('Subjek',validators=[DataRequired()])
    kategori= SelectField(u'Kategori Pengaduan', choices=[('administrasi','Pelayanan Administrasi'),('fasilitas','Fasilitas'), ('dosen','Dosen')], validators=[DataRequired()])
    detail_pengaduan= TextAreaField('Pengaduan')
    submit = SubmitField('Ubah')

class artikel_F(FlaskForm):
    judul = StringField('Judul artikel : ',validators=[DataRequired()])
    kategori= SelectField(u'Kategori artikel : ', choices=[('ikan','Ikan'),('Action','Aksi'), ('ternate','Ternate')], validators=[DataRequired()])
    detail_artikel= TextAreaField('Artikel')
    submit = SubmitField('Kirim')

class editartikel_F(FlaskForm):
    subjek = StringField('Subjek',validators=[DataRequired()])
    kategori= SelectField(u'Kategori artikel : ', choices=[('ikan','Ikan'),('Action','Aksi'), ('ternate','Ternate')], validators=[DataRequired()])
    detail_artikel= TextAreaField('Artikel')
    submit = SubmitField('Ubah')

class surat_F(FlaskForm):
    subjek = StringField('Pengirim : ',validators=[DataRequired()])
    kategori= SelectField(u'Kategori Surat : ', choices=[('HMJ','Hmj'),('Pemerintah','Pemerintah'), ('Kampus','Kamppus')], validators=[DataRequired()])
    detail_surat= TextAreaField('Isi Surat : ')
    submit = SubmitField('Kirim')

class editsurat_F(FlaskForm):
    subjek = StringField('Pengirim :',validators=[DataRequired()])
    kategori= SelectField(u'Kategori Surat', choices=[('HMJ','Hmj'),('Pemerintah','Pemerintah'), ('Kampus','Kamppus')], validators=[DataRequired()])
    detail_surat= TextAreaField('Pengaduan')
    submit = SubmitField('Ubah')

sim/mahasiswa/routes.py
from flask import Flask, render_template, redirect, url_for, Blueprint, flash,request
from sim.mahasiswa.forms import artikel_F, editmahasiswa_F, mahasiswa_F, loginmahasiswa_F, pengaduan_F, editpengaduan_F, artikel_F, editartikel_F, surat_F, editsurat_F
from sim.models import Tmahasiswa,Tpengaduan,Tartikel,Tsurat
from sim import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
import os
import secrets
from sim import app
from PIL import Image

rmahasiswa = Blueprint('rmahasiswa',__name__)

@rmahasiswa.route("/")
def home():
    return render_template("home.html")
    
@rmahasiswa.route("/about")
def about():
    return render_template("about.html")

@rmahasiswa.route("/data_mahasiswa", methods=['GET','POST'])
def data_m():
    form = mahasiswa_F()
    if form.validate_on_submit():
        pass_hash = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        add_mahasiswa=Tmahasiswa(npm=form.npm.data, nama=form.nama.data, email=form.email.data,
        password=pass_hash, kelas=form.kelas.data, alamat=form.alamat.data)
        db.session.add(add_mahasiswa)
        db.session.commit()
        flash(f'Akun-{form.npm.data} berhasil daftar','warning')
        return redirect(url_for('rmahasiswa.login_mahasiswa'))
    return render_template( "data-mahasiswa.html", form=form)

@rmahasiswa.route("/login_mahasiswa", methods=['GET','POST'])
def login_mahasiswa():
    if current_user.is_authenticated: 
        return redirect(url_for('rmahasiswa.home'))
    form = loginmahasiswa_F()
    if form.validate_on_submit():
        ceknpm = Tmahasiswa.query.filter_by(npm=form.npm.data).first()
        if ceknpm and bcrypt.check_password_hash(ceknpm.password, form.password.data):
            login_user(ceknpm)
            flash ('Selamat datang kembali', 'warning')
            return redirect(url_for('rmahasiswa.akunmahasiswa'))
        else:
            flash('Login gagal, Periksa NPM dan Password kembali','danger')

    return render_template( "login_mahasiswa.html", form=form)

@rmahasiswa.route("/akunmahasiswa")
@login_required
def akunmahasiswa():
    return render_template('akunmahasiswa.html')

@rmahasiswa.route("/logout_mahasiswa")
def logout_mahasiswa():
    logout_user()
    return redirect(url_for('rmahasiswa.home'))

#simpan foto
def simpan_foto(form_foto):
    random_hex= secrets.token_hex(8)
    f_name,f_ext = os.path.splitext(form_foto.filename)
    foto_fn= random_hex + f_ext
    foto_path= os.path.join(app.root_path, 'sim/static/foto',foto_fn)
    ubah_size= (300,300)
    j = Image.open(form_foto)
    j.thumbnail(ubah_size)
    j.save(foto_path)
    #form_foto.save(foto_path)
    return foto_fn

@rmahasiswa.route("/edit_mahasiswa", methods=['GET','POST'])
@login_required
def edit_mahasiswa():
    form=editmahasiswa_F()
    if form.validate_on_submit():
        if form.foto.data:
            file_foto= simpan_foto(form.foto.data)
            current_user.foto= file_foto
        pass_hash = bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        current_user.npm=form.npm.data
        current_user.nama=form.nama.data
        current_user.email=form.email.data
        current_user.kelas=form.kelas.data
        current_user.alamat=form.alamat.data
        current_user.password=pass_hash
        db.session.commit()
        flash('Data berhasil Di ubah', 'warning')
        return redirect(url_for('rmahasiswa.edit_mahasiswa'))
    elif request.method=="GET":
        form.npm.data=current_user.npm
        form.nama.data=current_user.nama
        form.email.data=current_user.email
        form.kelas.data=current_user.kelas
        form.alamat.data=current_user.alamat

    return render_template('edit_mahasiswa.html', form=form)

@rmahasiswa.route("/pengaduan", methods=['GET','POST'])
@login_required
def pengaduan():
    dt_pengaduan= Tpengaduan.query.filter_by(mahasiswa_id=current_user.id)
    form=pengaduan_F()
    if form.validate_on_submit():
        add_pengaduan=Tpengaduan(subjek=form.subjek.data, kategori=form.kategori.data, detail_pengaduan=form.detail_pengaduan.data, mahasiswa=current_user)
        db.session.add(add_pengaduan)
        db.session.commit()
        flash('Data berhasil dikirim','warning')
        return redirect(url_for('rmahasiswa.pengaduan'))
    return render_template ('pengaduan.html',form=form, dt_pengaduan= dt_pengaduan)

@rmahasiswa.route("/pengaduan/<int:ed_id>/update", methods=['GET','POST'])
@login_required
def update_pengaduan(ed_id):
    form=editpengaduan_F()
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    if request.method=="GET":
        form.subjek.data=dt_pengaduan.subjek
        form.kategori.data=dt_pengaduan.kategori
        form.detail_pengaduan.data=dt_pengaduan.detail_pengaduan
    
    elif form.validate_on_submit():
        dt_pengaduan.subjek=form.subjek.data
        dt_pengaduan.kategori=form.kategori.data
        dt_pengaduan.detail_pengaduan=form.detail_pengaduan.data
        db.session.commit()
        flash('Data berhasil diubah','warning')
        return redirect(url_for('rmahasiswa.pengaduan'))

    return render_template('edit_pengaduan.html', form=form)

@rmahasiswa.route("/delete/<id>", methods=['GET','POST'])
@login_required
def hapus_pengaduan(id):
    h_pengaduan=Tpengaduan.query.get(id)
    db.session.delete(h_pengaduan)
    db.session.commit()
    flash('Data berhasil di hapus','danger')
    return redirect(url_for('rmahasiswa.pengaduan'))

@rmahasiswa.route("/pengaduan/<int:ed_id>/detail", methods=['GET','POST'])
@login_required
def detail_pengaduan(ed_id):
    dt_pengaduan=Tpengaduan.query.get_or_404(ed_id)
    return render_template('detail_pengaduan.html', dt_pengaduan=dt_pengaduan)

@rmahasiswa.route("/artikel", methods=['GET','POST'])
@login_required
def artikel():
    dt_artikel= Tartikel.query.filter_by(mahasiswa_id=current_user.id)
    form = artikel_F()
    if form.validate_on_submit():
        add_artikel=Tartikel(judul=form.judul.data, kategori=form.kategori.data, detail_artikel=form.detail_artikel.data)
        db.session.add(add_artikel)
        db.session.commit()
        flash(f'Judul {form.judul.data} berhasil di upload','warning')
        return redirect(url_for('rmahasiswa.artikel'))
    return render_template("artikel.html", form=form, dt_artikel=dt_artikel)

@rmahasiswa.route("/artikel/<int:ed_id>/update", methods=['GET','POST'])
@login_required
def update_artikel(ed_id):
    form=editartikel_F()
    dt_artikel=Tartikel.query.get_or_404(ed_id)
    if request.method=="GET":
        form.judul.data=dt_artikel.judul
        form.kategori.data=dt_artikel.kategori
        form.detail_artikel.data=dt_artikel.detail_artikel
    
    elif form.validate_on_submit():
        dt_artikel.judul=form.judul.data
        dt_artikel.kategori=form.kategori.data
        dt_artikel.detail_artikel=form.detail_artikel.data
        db.session.commit()
        flash('Data berhasil diubah','warning')
        return redirect(url_for('rmahasiswa.artikel'))

    return render_template('edit_artikel.html', form=form)

@rmahasiswa.route("/surat", methods=['GET','POST'])
@login_required
def surat():
    dt_surat= Tsurat.query.filter_by(mahasiswa_id=current_user.id)
    form = surat_F()
    if form.validate_on_submit():
        add_surat=Tsurat(subjek=form.subjek.data, kategori=form.kategori.data, detail_surat=form.detail_surat.data, mahasiswa=current_user)
        db.session.add(add_surat)
        db.session.commit()
        flash(f'Surat {form.subjek.data} berhasil di upload','warning')
        return redirect(url_for('rmahasiswa.surat'))
    return render_template("surat.html", form=form, dt_surat=dt_surat)

@rmahasiswa.route("/surat/<int:ed_id>/update", methods=['GET','POST'])
@login_required
def update_surat(ed_id):
    form=editsurat_F()
    dt_surat=Tsurat.query.get_or_404(ed_id)
    if request.method=="GET":
        form.subjek.data=dt_surat.subjek
        form.kategori.data=dt_surat.kategori
        form.detail_surat.data=dt_surat.detail_surat
    
    elif form.validate_on_submit():
        dt_surat.subjek=form.subjek.data
        dt_surat.kategori=form.kategori.data
        dt_surat.detail_pengaduan=form.detail_surat.data
        db.session.commit()
        flash('Data berhasil diubah','warning')
        return redirect(url_for('rmahasiswa.surat'))

    return render_template('edit_surat.html', form=form)

@rmahasiswa.route("/surat/<int:ed_id>/detail", methods=['GET','POST'])
@login_required
def detail_surat(ed_id):
    dt_surat=Tsurat.query.get_or_404(ed_id)
    return render_template('detail_surat.html', dt_surat=dt_surat)

@rmahasiswa.route("/delet/<id>", methods=['GET','POST'])
@login_required
def hapus_surat(id):
    h_surat=Tsurat.query.get(id)
    db.session.delete(h_surat)
    db.session.commit()
    flash('Data berhasil di hapus','danger')
    return redirect(url_for('rmahasiswa.surat'))

sim/templates/about.html
{% extends "base.html" %} 
{% block content %}


<h1>Daily Quotes</h1>
<p>"jika dalam menghadapi suatu masalah kita tidak menemukan jalan keluar, maka kita yang harus keluar untuk jalan-jalan"</p>

{% endblock content %}

sim/templates/akunmahasiswa.html
{% extends "base.html" %} 
{% block content %}

<div class="jumbotron">
  <h1 class="display-4">HELLO, {{current_user.nama}}</h1>
  <p class="lead">"Selamat Datang di Sistem Informasi Pengaduan, Semoga Pengaduan Anda Menjadi Perbaikan Kami"</p>
  <hr class="my-4">
  <p>Untuk Melakukan Pengaduan, silahkan klik di bawah!</p>
    <p class="lead">
      <a class="btn btn-warning btn-lg" href="{{url_for('rmahasiswa.pengaduan')}}" role="button">pengaduan</a>
    </p>
  </div>

{% endblock content %}

sim/templates/base.html
<html>
<head>
    <title>latihan</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSS only -->
    <link href=" {{ url_for ('static', filename = "css/bootstrap.min.css")}}" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href=" {{ url_for ('static', filename = "css/style.css")}}">
    <td width="30" align="center"><img src="{{ url_for ('static', filename="logo op.png")}}" width="15%"></td>

  </head>
<body style="background-color: rgba(34, 34, 34, 0.721);">
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgb(15, 15, 15); color:white">
    <div class="container">
            <a class="navbar-brand" href="#" style="color: white;">   
            </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{{url_for('rmahasiswa.home')}}" style="color: white;">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('rmahasiswa.about')}}" style="color: white;">About</a>
              </li>
              {% if current_user.is_authenticated %}
              -------------user
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{url_for('rmahasiswa.login_mahasiswa')}}" style="color: white;">Login Mahasiswa</a>
              </li>
              {% endif %}
              <!--dropdown
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li>
              -->
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
    </div>
  </nav>
      <div class="container mt-4">
        <div class="row">
          <div class="col-md-8">
            <div class="shadow p-3 mb-5 bg-white rounded">
              <!--FLash-->
              {% with messages = get_flashed_messages(with_categories = true) %}
              {% if messages %}
              {% for category, message in messages %}
              <div class="alert alert-{{category}}">
                  {{message}}
              </div>
              {% endfor %}
              {% endif %}
              {% endwith %}

            {%block content%}
            {%endblock content%}
            </div>
          </div>
          <div class="col-md-4">
            <div class="shadow p-3 mb-5 bg-white rounded">
              <ul>
                {%if current_user.is_authenticated%}
                <div class="card" style="width: 13rem;">
                  <img src=" {{ url_for ('static', filename='foto/' + current_user.foto)}}" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">{{current_user.nama}}</h5>
                    <p class="card-text">{{current_user.email}}</p>
                  </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item"><a href="{{url_for('rmahasiswa.akunmahasiswa')}}">Dasboard</a></li>
                    <li class="list-group-item"><a href="{{url_for('rmahasiswa.pengaduan')}}">Pengaduan</a></li>
                    <li class="list-group-item"><a href="{{url_for('rmahasiswa.artikel')}}">Artikel</a></li>
                    <li class="list-group-item"><a href="{{url_for('rmahasiswa.surat')}}">surat</a></li>
                  </ul>
                  <div class="card-body">
                    <a href="{{url_for('rmahasiswa.edit_mahasiswa')}}" class="card-link">Update Profil</a>
                    <a href="{{url_for('rmahasiswa.logout_mahasiswa')}}" class="card-link">logout</a>
                  </div>
                </div>
                {% else %}
                <h1>Menu Lain</h1>
                <li>Data Mahasiswa</li>
                <li>Data Dosen</li>
                {% endif %}
              </ul>
            </div>
          </div>
      </div>
    </div>
 <!-- JavaScript Bundle with Popper -->
 <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
 <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
 <script src="{{ url_for ('static', filename = "js/bootstrap.min.js")}}" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

sim/templates/home.html
{% extends "base.html" %} 
{% block content %}
<div class="jumbotron">
  <h1 class="display-4">Welcome Guys</h1>
  <p class="lead">"Perubahan Tidak Datang Dari Kaki Yang Diam"</p>
  <hr class="my-4">
  <p></p>
  <p></p>
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>
{% endblock content %}

sim/templates/login_mahasiswa.html
{% extends "base.html" %} 
{% block content %}

<h1>Login Akun </h1>

<form method="POST">
    {{ form.hidden_tag()}}
    <div class="form-group">
        {{form.npm.label(class="form-control-label")}}
        {% if form.npm.errors %}
            {{form.npm(class="form-control is-invalid")}}
        
            <div class="invalid-feedback">
                {% for error in form.npm.errors %}
               <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.npm(class="form-control")}}

        {% endif %}
    </div>
    <div class="form-group">
      {{form.password.label(class="form-control-label")}}
      {% if form.password.errors %}
          {{form.password(class="form-control is-invalid")}}
      
            <div class="invalid-feedback">
                {% for error in form.password.errors %}
              <span>{{error}}</span>
                {% endfor %}
           </div>
      {% else %}
          {{form.password(class="form-control")}}

      {% endif %}
    </div>

    <br>
    <div class="form-group">
      {{form.submit(class="btn btn-primary")}}     
    </div>

    <span> <a href=" {{url_for('rmahasiswa.data_m')}} ">Daftar</a></span>

  </form>
{% endblock content %}

sim/templates/pengaduan.html
{% extends "base.html" %} 
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

<div class="jumbotron">
    <h4>Pengaduan</h4>
    <!--Data Pengaduan-->
    <form method="POST">
      {{ form.hidden_tag()}}
      <div class="form-group">
          {{form.subjek.label(class="form-control-label")}}
          {% if form.subjek.errors %}
              {{form.subjek(class="form-control is-invalid")}}
          
              <div class="invalid-feedback">
                  {% for error in form.subjek.errors %}
                 <span>{{error}}</span>
                  {% endfor %}
              </div>
          {% else %}
              {{form.subjek(class="form-control")}}
  
          {% endif %}
      </div>

      <div class="form-group">
        {{form.kategori.label(class="form-control-label")}}
        {% if form.kategori.errors %}
            {{form.kategori(class="form-control is-invalid")}}
        
            <div class="invalid-feedback">
                {% for error in form.kategori.errors %}
               <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.kategori(class="form-control")}}

        {% endif %}
      </div>

      <div class="form-group">
        {{form.detail_pengaduan.label(class="form-control-label")}}
        {% if form.detail_pengaduan.errors %}
            {{form.detail_pengaduan(class="form-control is-invalid")}}
        
            <div class="invalid-feedback">
                {% for error in form.detail_pengaduan.errors %}
               <span>{{error}}</span>
                {% endfor %}
            </div>
        {% else %}
            {{form.detail_pengaduan(class="form-control")}}

        {% endif %}
      </div>
      
      <br>
      <div class="form-group">
        {{form.submit(class="btn btn-primary")}}     
      </div>
    </form>

    <script>
      function klik_hapus(value){
        let valid_link = document.getElementById('del-hapus')
        valid_link.href="/delete/ " + value
      }
    </script>

    <hr class="my-4">
    <h4>Data Pengaduan</h4>
    <div class="table-responsive">

        <table class="table table-hover table-dark">
            <thead>
              <tr>
                <th scope="col">No.</th>
                <th scope="col">Tanggal</th>
                <th scope="col">Subjek</th>
                <th scope="col">Kategori</th>
                <th scope="col">Edit</th>
                <th scope="col">Hapus</th>
              </tr>
            </thead>
            <tbody>
                {% for data in dt_pengaduan %}
              <tr>
                <th scope="row">
                  <a href=" {{url_for('rmahasiswa.detail_pengaduan', ed_id=data.id)}} ">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down-left-square-fill" viewBox="0 0 16 16">
                      <path d="M2 16a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2zm8.096-10.803L6 9.293V6.525a.5.5 0 0 0-1 0V10.5a.5.5 0 0 0 .5.5h3.975a.5.5 0 0 0 0-1H6.707l4.096-4.096a.5.5 0 1 0-.707-.707z"/>
                    </svg>
                  </a>
                </th>
                <td>{{data.tgl_post}}</td>
                <td>{{data.subjek}}</td>
                <td>{{data.kategori}}</td>
                <td><a class="btn btn-outline-light" href="{{url_for('rmahasiswa.update_pengaduan', ed_id=data.id)}}">Edit</a></td>
                <td><a class="btn btn-outline-danger" data-toggle="modal" data-target="#modals-hapus" onclick="klik_hapus({{data.id}})" >Hapus</a></td>
              </tr>
              {%endfor%}
              <!-- modals Delete-->         
              <div class="modal" tabindex="-1" role="dialog" id="modals-hapus">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title">Modal title</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p>Modal body text goes here.</p>
                    </div>
                    <div class="modal-footer">
                      <form action="">
                        <a class="btn btn-danger" id="del-hapus"> Hapus</a>
                      </form>
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>
            </tbody>
          </table>
          
    </div>

</div>

{% endblock content %}